services:
  sut:  
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: sut_test
    command: ["pytest", "tests/", "-v"]
    environment:
      ENVIRONMENT: testing
      DATABASE_URL: postgresql://frankhz_test:testpassword@postgres-test-db:5432/demanda_test
    depends_on:
      postgres-test-db:
        condition: service_started

  postgres-test-db:
    image: postgres:15-alpine
    container_name: condor_postgres_test_ci
    environment:
      POSTGRES_USER: frankhz_test
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: demanda_test
    tmpfs:
      - /var/lib/postgresql/data